# Use a specific version of node:alpine for better reproducibility
FROM node:alpine

# Set the working directory in the container
WORKDIR /usr/app

# First copy only package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Then copy the rest of the application's source code
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["node", "server.js"]
